services:
  - type: web
    name: seatreserve-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health/liveness
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_PASSWORD
        sync: false
      - key: REDIS_SSL
        value: "false"
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: "86400000"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://seat-reserve-xi.vercel.app,https://seat-reserve-git-main-varunkalambe4294-7255s-projects.vercel.app"
      - key: CORS_ALLOW_VERCEL_PREVIEWS
        value: "true"
      - key: WALLET_DEMO_TOP_UP_ENABLED
        value: "true"
      - key: APP_TIMEZONE
        value: "Asia/Kolkata"
      - key: RATE_LIMIT_PER_MINUTE
        value: "60"
      - key: JPA_DDL_AUTO
        value: "update"
      - key: LOG_LEVEL_APP
        value: "INFO"
